HASH_OUTPUT_BIT_SIZE = 128
HASH_OUTPUT_TMAX = 2**HASH_OUTPUT_BIT_SIZE - 1
ID_BIT_SIZE = HASH_OUTPUT_BIT_SIZE - 1 # because Python only has signed ints
ID_TRUE_VALUE_BIT_SIZE = 2
ID_PLAYER_BIT_SIZE = 1
