HASH_OUTPUT_BIT_LENGTH = 128
HASH_OUTPUT_TMAX = 2**HASH_OUTPUT_BIT_LENGTH - 1
ID_BIT_LENGTH = HASH_OUTPUT_BIT_LENGTH - 1 # because Python only has signed ints
ID_TRUE_VALUE_BIT_LENGTH = 2
ID_PLAYER_BIT_LENGTH = 1
